server:
    port: 8080
    servlet:
        context-path:

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/learn"
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true